### ISSUE TITLE
windows11无法启动

### ISSUE THREAD

**Issue by hjp070928** [moonheart/Clasharp#12]
windows11无法启动

**Comment by moonheart** [comment]
请看下程序目录下是否有 log.log 文件， 有的话把内容上来看看

**Comment by hiddify1** [comment]
``` 
2023-03-15 21:37:52.612 +01:00 [ERR] Exception from InteractionContext
(Line: 12, Col: 18, Idx: 208) - (Line: 12, Col: 31, Idx: 221): Exception during deserialization

```

**Comment by moonheart** [comment]
@hiddify1 请把你的配置脱敏(服务器地址,订阅地址)后发上来我测试一下

**Comment by githenrycheung** [comment]
错误信息,路径不对，本来想移到对应目录，但是程序名称也对不上
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\xxxxxx\.config\clasharp\clash-meta.exe' with working directory 'C:\Users\xxxxxx\.config\clasharp'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Clasharp.Common.ClashWrapper.Test()
   at Clasharp.Cli.ClashCliBase.GenerateConfig() in D:\a\Clasharp\Clasharp\Clasharp\Cli\ClashCliBase.cs:line 96
   at Clasharp.Cli.ClashCliBase.Start() in D:\a\Clasharp\Clasharp\Clasharp\Cli\ClashCliBase.cs:line 66
   at Clasharp.Cli.ClashCli.Start() in D:\a\Clasharp\Clasharp\Clasharp\Cli\ClashCli.cs:line 60
   at Clasharp.ViewModels.ClashInfoViewModel.<>c__DisplayClass0_0.<<-ctor>b__4>d.MoveNext() in D:\a\Clasharp\Clasharp\Clasharp\ViewModels\ClashInfoViewModel.cs:line 35
